version: "3.9" #This denotes that we are using version 3 of Docker Compose
services: #This section defines all the different containers we will create.
  find-my-kids: #This is the name of our Nextjs application.
    build:
      context: .
      dockerfile: Dockerfile
    container_name: find-my-kids
    image: find-my-kids
    ports:
      - "3001:3000"

    env_file:
      - .env
    restart: unless-stopped